package setty.dispatch.domain;

public enum DispatchStatus {
    SELLER_INPUT_PENDING,
    FINAL_REVIEW_PENDING,
    FINAL_AMOUNT_CONFIRM_PENDING,
    DISPATCH_PENDING,
    DISPATCH_COMPLETED,
    IN_TRANSIT,
    DELIVERY_COMPLETED,
    FINAL_AMOUNT_REJECTED,
    TRANSPORT_INFEASIBLE,
    USER_CANCELLED,
    DISPATCH_FAILED
}
