aws:
  s3:
    region: ap-northeast-2
    bucket-name: techcourse-project-2026
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/setty
    username: setty
    password: setty
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
server:
  error:
    include-message: never
    include-stacktrace: never
setty:
  operator:
    secret: ${SETTY_OPERATOR_SECRET:}
  dispatch:
    front-base-url: ${SETTY_FRONT_BASE_URL:http://localhost:3000}
